import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ReactNode } from 'react';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header className="bg-blue-600 text-white p-4">
          <h1 className="text-2xl font-bold">Global Header</h1>
          <nav>
            <a href="/" className="mr-4">Home</a>
            <a href="/dashboard" className="mr-4">Dashboard</a>
            <a href="/profile">Profile</a>
          </nav>
        </header>
        <main className="min-h-screen p-6">{children}</main>
        <footer className="bg-gray-800 text-white text-center p-4">
          <p>&copy; 2024 My App</p>
        </footer>
      </body>
    </html>
  );
}